"""API routes for Jingxin-Agent."""

from .files import router as files_router

# V1 API routes
from .v1 import (
    chats_router,
    users_router,
    catalog_v1_router,
    kb_router,
    audit_router,
    summary_router,
    classify_router,
    config_router,
    file_parse_router,
    file_upload_router,
    content_router,
    memories_router,
    auth_router,
    mock_sso_router,
    models_router,
    service_configs_router,
    admin_skills_router,
    admin_prompts_router,
    admin_mcp_servers_router,
    chat_shares_router,
    agents_router,
    admin_agents_router,
    artifacts_router,
    plans_router,
    config_verify_router,
    admin_usage_logs_router,
    admin_billing_router,
    admin_chat_history_router,
    code_execute_router,
    automations_router,
    admin_logs_router,
)

__all__ = [
    "files_router",
    "chats_router",
    "users_router",
    "catalog_v1_router",
    "kb_router",
    "audit_router",
    "summary_router",
    "classify_router",
    "config_router",
    "file_parse_router",
    "file_upload_router",
    "content_router",
    "memories_router",
    "auth_router",
    "mock_sso_router",
    "models_router",
    "service_configs_router",
    "admin_skills_router",
    "admin_prompts_router",
    "admin_mcp_servers_router",
    "chat_shares_router",
    "agents_router",
    "admin_agents_router",
    "artifacts_router",
    "plans_router",
    "config_verify_router",
    "admin_usage_logs_router",
    "admin_billing_router",
    "admin_chat_history_router",
    "code_execute_router",
    "automations_router",
    "admin_logs_router",
]
