"""Initial migration: create all tables

Revision ID: 98eae3311185
Revises: 
Create Date: 2026-02-13 19:14:30.245574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98eae3311185'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_shadow',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('user_center_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_users_shadow_updated_at', 'users_shadow', ['updated_at'], unique=False)
    op.create_index('idx_users_shadow_user_center_id', 'users_shadow', ['user_center_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('success', 'failure', 'error')", name='audit_logs_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shadow.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_status', 'audit_logs', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status != 'success'"))
    op.create_index('idx_audit_logs_trace_id', 'audit_logs', ['trace_id'], unique=False)
    op.create_index('idx_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('catalog_overrides',
    sa.Column('override_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('skill', 'agent', 'mcp')", name='catalog_overrides_kind_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shadow.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_id'),
    sa.UniqueConstraint('user_id', 'kind', 'item_id', name='catalog_overrides_unique_user_kind_item')
    )
    op.create_index('idx_catalog_overrides_kind', 'catalog_overrides', ['kind', 'enabled'], unique=False)
    op.create_index('idx_catalog_overrides_user_id', 'catalog_overrides', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(title) >= 1', name='chat_sessions_title_length'),
    sa.CheckConstraint('message_count >= 0', name='chat_sessions_message_count_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shadow.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index('idx_chat_sessions_deleted', 'chat_sessions', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_chat_sessions_favorite', 'chat_sessions', ['user_id', 'favorite', 'updated_at'], unique=False, postgresql_where=sa.text('favorite = true'))
    op.create_index('idx_chat_sessions_metadata_gin', 'chat_sessions', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_chat_sessions_pinned', 'chat_sessions', ['user_id', 'pinned', 'updated_at'], unique=False, postgresql_where=sa.text('pinned = true'))
    op.create_index('idx_chat_sessions_updated_at', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_chat_sessions_user_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('kb_spaces',
    sa.Column('kb_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(name) >= 1 AND char_length(name) <= 255', name='kb_spaces_name_length'),
    sa.CheckConstraint('document_count >= 0', name='kb_spaces_document_count_check'),
    sa.CheckConstraint('total_size_bytes >= 0', name='kb_spaces_total_size_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shadow.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kb_id')
    )
    op.create_index('idx_kb_spaces_deleted', 'kb_spaces', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_kb_spaces_updated_at', 'kb_spaces', ['updated_at'], unique=False)
    op.create_index('idx_kb_spaces_user_id', 'kb_spaces', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('report', 'chart', 'document', 'code', 'other')", name='artifacts_type_check'),
    sa.CheckConstraint('size_bytes > 0', name='artifacts_size_check'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.chat_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shadow.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('idx_artifacts_chat_id', 'artifacts', ['chat_id'], unique=False)
    op.create_index('idx_artifacts_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index('idx_artifacts_deleted', 'artifacts', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_artifacts_type', 'artifacts', ['type'], unique=False)
    op.create_index('idx_artifacts_user_created', 'artifacts', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_artifacts_user_id', 'artifacts', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='chat_messages_role_check'),
    sa.CheckConstraint('char_length(content) <= 100000', name='chat_messages_content_length'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_chat_messages_chat_created', 'chat_messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_chat_messages_chat_id', 'chat_messages', ['chat_id'], unique=False)
    op.create_index('idx_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('idx_chat_messages_role', 'chat_messages', ['chat_id', 'role'], unique=False)
    op.create_index('idx_chat_messages_tool_calls_gin', 'chat_messages', ['tool_calls'], unique=False, postgresql_using='gin', postgresql_where=sa.text('tool_calls IS NOT NULL'))
    op.create_table('kb_documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(filename) >= 1', name='kb_documents_filename_length'),
    sa.CheckConstraint('size_bytes > 0', name='kb_documents_size_check'),
    sa.ForeignKeyConstraint(['kb_id'], ['kb_spaces.kb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('idx_kb_documents_deleted', 'kb_documents', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_kb_documents_kb_id', 'kb_documents', ['kb_id'], unique=False)
    op.create_index('idx_kb_documents_kb_uploaded', 'kb_documents', ['kb_id', 'uploaded_at'], unique=False)
    op.create_index('idx_kb_documents_metadata_gin', 'kb_documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_kb_documents_uploaded_at', 'kb_documents', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kb_documents_uploaded_at', table_name='kb_documents')
    op.drop_index('idx_kb_documents_metadata_gin', table_name='kb_documents', postgresql_using='gin')
    op.drop_index('idx_kb_documents_kb_uploaded', table_name='kb_documents')
    op.drop_index('idx_kb_documents_kb_id', table_name='kb_documents')
    op.drop_index('idx_kb_documents_deleted', table_name='kb_documents', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('kb_documents')
    op.drop_index('idx_chat_messages_tool_calls_gin', table_name='chat_messages', postgresql_using='gin', postgresql_where=sa.text('tool_calls IS NOT NULL'))
    op.drop_index('idx_chat_messages_role', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('idx_chat_messages_chat_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_chat_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_artifacts_user_id', table_name='artifacts')
    op.drop_index('idx_artifacts_user_created', table_name='artifacts')
    op.drop_index('idx_artifacts_type', table_name='artifacts')
    op.drop_index('idx_artifacts_deleted', table_name='artifacts', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_artifacts_created_at', table_name='artifacts')
    op.drop_index('idx_artifacts_chat_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_kb_spaces_user_id', table_name='kb_spaces')
    op.drop_index('idx_kb_spaces_updated_at', table_name='kb_spaces')
    op.drop_index('idx_kb_spaces_deleted', table_name='kb_spaces', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('kb_spaces')
    op.drop_index('idx_chat_sessions_user_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated_at', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_pinned', table_name='chat_sessions', postgresql_where=sa.text('pinned = true'))
    op.drop_index('idx_chat_sessions_metadata_gin', table_name='chat_sessions', postgresql_using='gin')
    op.drop_index('idx_chat_sessions_favorite', table_name='chat_sessions', postgresql_where=sa.text('favorite = true'))
    op.drop_index('idx_chat_sessions_deleted', table_name='chat_sessions', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('chat_sessions')
    op.drop_index('idx_catalog_overrides_user_id', table_name='catalog_overrides')
    op.drop_index('idx_catalog_overrides_kind', table_name='catalog_overrides')
    op.drop_table('catalog_overrides')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_trace_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_status', table_name='audit_logs', postgresql_where=sa.text("status != 'success'"))
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_shadow_user_center_id', table_name='users_shadow')
    op.drop_index('idx_users_shadow_updated_at', table_name='users_shadow')
    op.drop_table('users_shadow')
    # ### end Alembic commands ###
