"""add tools_json to admin_mcp_servers

Revision ID: c19b17bb0e6c
Revises: f6g7h8i9j0k1
Create Date: 2026-03-25 09:54:36.052204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c19b17bb0e6c'
down_revision: Union[str, Sequence[str], None] = 'f6g7h8i9j0k1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_mcp_servers', sa.Column('tools_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_mcp_servers', 'tools_json')
    # ### end Alembic commands ###
