"""add expected_skills to plan_steps

Revision ID: eea1fd495093
Revises: 585973f31e2f
Create Date: 2026-04-07 10:15:45.913662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea1fd495093'
down_revision: Union[str, Sequence[str], None] = '585973f31e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_steps', sa.Column('expected_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_steps', 'expected_skills')
    # ### end Alembic commands ###
